[book]
authors = ["the pace authors"]
description = "pace - Mindful Time Tracking: Simplify Your Focus and Boost Productivity Effortlessly."
language = "en"
multilingual = false
src = "src"
title = "pace user documentation"

[preprocessor.last-changed]
command = "mdbook-last-changed"
renderer = ["html"]

[output.html]
curly-quotes = true
default-theme = "ayu"
site-url = "/docs/"
git-repository-url = "https://github.com/pace-rs/docs"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/pace-rs/docs/edit/main/{path}"
cname = "pace.cli.rs"
additional-css = ["./styles/last-changed.css"]

[output.html.fold]
enable = true
level = 0

[output.html.redirect]
# Redirects in the form of "old-path" = "new-path", where the new path
# is relative to the old path.
"getting_started.html" = "user_guide/getting_started.html"
"FAQ.html" = "user_guide/FAQ.html"
"installation.html" = "user_guide/installation.html"
